version: '3.8'

services:
  web:
    env_file:
      - .env
    build: .
    container_name: django-web-container
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            ./admin.sh &&
            gunicorn --bind 0.0.0.0:8000 json_api.wsgi:application"
    volumes:
      - django_shared_static:/app/staticfiles # Статика Django
      - django_shared_media:/app/media              # Медиафайлы
      # - ./db.sqlite3:/app/db.sqlite3
    networks:
      - shared_net # Добавляем в общую сеть
    expose:
      - 8000

networks:
  shared_net:
    external: true
    name: shared_network

volumes:
  django_shared_media:
    external: true
  django_shared_static:
    external: true
